[package]
name = "grpc-actix"
version = "0.1.0"
authors = ["Theodore Cipicchio <okready@users.noreply.github.com>", "Sascha Wise <me@saschawise.com>"]
description = "Actor-based gRPC client and server implementation"

[dependencies]
actix = "0.7"
futures = "0.1"
tokio = "0.1"